export const actions = {
  ADD_SCHEDULE: "ADD_SCHEDULE",
  REMOVE_SCHEDULE: "REMOVE_SCHEDULE",
  ADD_RESERVATION: "ADD_RESERVATION",
  REMOVE_RESERVATION: "REMOVE_RESERVATION",
  CONFIRM_RESERVATION: "CONFIRM_RESERVATION"
};
